[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta:__legacy__"


[tool.ruff]
line-length = 88
select = ["E", "F", "I", "U", "N", "ERA", "C", "B", "A", "M001"]
# Interesting: "D", for docstrings
# src = ["setup.py", "rvo/"]